version: 2.1
orbs:
    cypress: cypress-io/cypress@1
executors:
    with-chrome:
        docker:
            - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
    build:
        jobs:
            - cypress/run:
                  executor: with-chrome
                  command: npm run test-full
                  store_artifacts: true
                  post-steps:
                      - run:
                            name: Merge Reports
                            command: npm run report-merge
                            when: always
                      - run:
                            name: Generate HTML Report
                            command: npm report-html
                            when: always
                      - run:
                            name: Upload to Calliope
                            command: |
                                curl='curl -X POST "https://app.calliope.pro/api/v2/profile/${CALLIOPE_PROFILE_ID}/import/mochawesome" -H "x-api-key:${CALLIOPE_API_KEY}" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "file[]=@cypress/reports/output.json;type=application/json" -F "envelope=false" -F "smart=true"'
                                eval $curl
                            when: always
                      - store_artifacts:
                            path: cypress/reports/mocha/output
                      - store_test_results:
                            path: cypress/reports/junit
