version: 2.1
orbs:
    cypress: cypress-io/cypress@1
executors:
    with-chrome:
        docker:
            - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
    build:
        jobs:
            - cypress/run:
                  executor: with-chrome
                  command: npm run test-full
                  store_artifacts: true
                  post-steps:
                      - run:
                            name: Merge Reports
                            command: npx mochawesome-merge cypress/reports/mocha/*.json > cypress/reports/output.json
                            when: always
                      - run:
                            name: Generate HTML Report
                            command: npx marge cypress/reports/output.json --reportDir cypress/reports/mocha/output --inline
                            when: always
                      - run:
                            name: Upload to Calliope
                            command: bash -c "$CALLIOPE_CURL"
                            when: always
                      - store_artifacts:
                            path: cypress/reports/mocha/output
                      - store_test_results:
                            path: cypress/reports/junit
