version: 2.1
orbs:
    cypress: cypress-io/cypress@1
executors:
    with-chrome:
        docker:
            - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
    build:
        jobs:
            - cypress/run:
                  executor: with-chrome
                  command: npm run test-full
                  store_artifacts: true
                  post-steps:
                      - run: npx mochawesome-merge cypress/reports/mocha/*.json > cypress/reports/output.json
                      - run: npx marge cypress/reports/output.json --reportDir cypress/reports/mocha/output --inline
                      - store_artifacts:
                            path: cypress/reports/mocha/output
